### ISSUE TITLE
Error: File to import not found or unreadable

### ISSUE THREAD

**Issue by indeedwatson** [guglicap/wal-discord#1]
I symlinked the files according to the wiki to `~/.config/wal-discord`, and I ran `. ~/wal-discord/wal-discord`.

First I got:
```bash
dirname: missing operand
Try 'dirname --help' for more information.
Error: File to import not found or unreadable: backend.scss.
       Parent style sheet: /home/yama/.config/wal-discord/master.scss
        on line 1 of ../.config/wal-discord/master.scss
>> @import "backend.scss";
   ^
```

Reading more of the wiki, it seems to imply that wal-discord will symlink one of the backends to `backend.scss`, since it didn't, I did it manually, and upon executing again I get:

```bash
dirname: missing operand
Try 'dirname --help' for more information.
Error: File to import not found or unreadable: colors.scss.
       Parent style sheet: /home/yama/.config/wal-discord/backend.scss
        on line 1 of ../.config/wal-discord/backend.scss
>> @import 'colors.scss';
   ^
```

**Comment by guglicap** [comment]
As a quick fix you can symlink `$HOME/.cache/wal/colors.scss` to `$HOME/.config/wal-discord/colors.scss`

Before doing that, could you post the output of `ls -l $HOME/.config/wal-discord/`, so that I can look into what went wrong? 

I think that, since `wal-discord` was run by specifying the absolute path to the script, [this line](https://github.com/guglicap/wal-discord/blob/2ae31eeb8540dde07fe4e9e8749753b9f1f48099/wal-discord#L42) failed to execute and thus the inital setup failed.

**Comment by indeedwatson** [comment]
```bash
 ✗ ~/.config/wal-discord ls -l $HOME/.config/wal-discord   
total 0
lrwxrwxrwx 1 yama yama 39 May 23 10:26 backends -> /home/yama/wal-discord/config/backends/
lrwxrwxrwx 1 yama yama 48 May 23 10:28 backend.scss -> /home/yama/.config/wal-discord/backends/wal.scss
lrwxrwxrwx 1 yama yama 41 May 23 10:20 master.scss -> /home/yama/wal-discord/config/master.scss
lrwxrwxrwx 1 yama yama 34 May 23 10:32 wal-discord -> /home/yama/wal-discord/wal-discord
```
Actually, I also executed by cd'ing into `~/wal-discord` and doing `./wal-discord`.
