### ISSUE TITLE
Support for double dash '--' style arguments

### ISSUE THREAD

**Issue by sambnh** [guglicap/wal-discord#13]
Running `wal-discord --help` outputs the expected usage text preceded by 
`/home/user/.local/bin/wal-discord: illegal option -- -`.

This appears to be due to the fact that `--` style arguments are not supported,
resulting in the arguments being evaluated the same way as `wal-discord -- -h -e -l -p`. In addition to this, the script doesn't state that e, l and p are illegal options, I expect this is due to the script not checking for illegal options after a correct one is found (e.g. -h).

Double dash style arguments are widely used and would be a nice additional feature. If they're not included they should at least be accounted for in the validation phase before executing the arguments.

**Comment by guglicap** [comment]
Alright, so, I've been looking into this but to be honest I don't think I will change it. I think right now it's handling command line arguments in the cleanest way possible, using bash internal getopts command, which guarantees it will work on other systems such as macOS. It seems like I could rewrite it using enhanced getopts from glibc but then it won't work on macOS out of the box. To be honest I don't think double dash argument support is a crucial feature. Also, it doesn't mention that `-e`, `-l` and `-p` are illegal options because as soon as `-h` is found the script will print the help message and exit.

**Comment by sambnh** [comment]
That certainly makes sense, it seems like a lot of work for a minor change. Thank you for taking the time to give an explanation, I very much appreciate it.

**Comment by guglicap** [comment]
No problem, thank you for your input as well. Have a nice day.
