### ISSUE TITLE
Missing documentation on how to use wpgtk with wal-discord

### ISSUE THREAD

**Issue by Poroing** [guglicap/wal-discord#18]
It seems that youre last commit has introduced the possibility to use wpgtk has the source for the colors. When using wpgtk, this commit searches for the `colors.scss` file in the `${HOME}/.config/wpg/formats/` directory. However, I can't seem to find how this file should be generated.

Is this file supposed to be generated using a template, or is it generated automatically by wpgtk?

I believe that the wiki should be extended with this information. I'm willing to do it if I find out how to contribute to the wiki.

**Comment by guglicap** [comment]
It is generated automatically by wpgtk.

**Comment by Poroing** [comment]
This file is not produced by my installation of wpgtk and I can't find any mention of this file in the wpgtk documentation. Is there anything missing in my configuration to produce this file, here is how my configuration looks like:
```
[settings]
set_wallpaper = true
gtk = true
active = 0
light_theme = false
editor = urxvt -e vim
execute_cmd = false
command = urxvt -e echo hi
backend = wal
alpha = 100
smart_sort = true
auto_adjust = false

[keywords]
```

**Comment by guglicap** [comment]
@Poroing actually, I installed wpgtk to test this and it seems to be using `wal` under the hood, which means that it should work anyway as the script should fall back to the `.cache/wal/colors.scss` file. And indeed, it worked when I tested it.

**Comment by VGrol** [comment]
@guglicap Yup, with some caveats.
Wal is depreciated for pywal, which is a rewrite of the project. WPGTK is in turn a wrapper with some UI and additional features for pywal and uses the exact same file structure.
If I recall correctly wpgtk and pywal both did some... funky changes to their default colour files, but these days they're compatible with the old wal format. 

I did some digging and I think the `WPG_COLORS` variable and check can be considered depreciated due to the very nature of wpgtk these days, since the /formats folder is depreciated in favor of `~/.cache/wal/colors.scss`.

**Comment by guglicap** [comment]
@VGrol thanks for the insight. Then yes, I can close this issue and maybe merge a PR to remove the variable.
