### ISSUE TITLE
Theme fails to apply to Discord

### ISSUE THREAD

**Issue by GideonWolfe** [guglicap/wal-discord#23]
So I got `wal-discord` working perfectly on my laptop after I used the `-t` flag.

![2020-05-24-194902_2560x1600_scrot](https://user-images.githubusercontent.com/32942052/82773901-2bc4f600-9df8-11ea-9e69-623bc7b45ecf.png)

I replicated my process *exactly* on my desktop running an *identical* setup with i3, `betterdiscord`, and `wal-discord`, using the same wallpaper. Here's what the theme looks like on my desktop

![disc](https://user-images.githubusercontent.com/32942052/82774000-6b8bdd80-9df8-11ea-943a-3d974a7b7e79.png)

**Comment by guglicap** [comment]
is the discord version the same?

**Comment by GideonWolfe** [comment]
When I run `discord -v` on both devices, the first line is 
```
Discord 0.0.10
```
So I think so? Both were downloaded today from the Arch repositories

**Comment by VGrol** [comment]
I think `Discord -v` is kind of broken, it tends to do it's own updating thing that isn't that easy to check.
Do make sure you're actually running discord and not something like discord-canary.

the CSS on your desktop looks an awful lot like the unfixed css of last week.
could you make sure the repo is up to date and the `master.scss` file is properly linked and up to date?

Other than that I've ran into some CSS buggyness with betterdiscord, beautifuldiscord might be worth a shot if that doesn't help.

**Comment by GideonWolfe** [comment]
I have

1. Updated the `wal-discord` repository
2. Completely reinstalled `Discord`
3. Completely reinstalled `Betterdiscord`
4. Completely reinstalled `betterdiscordctl`
5. Removed and regenerated the `wal_discord` theme file.

Still the ugly theme persists...

**Comment by VGrol** [comment]
I don't have too much knowledge of betterdiscord, besides the fact that the base betterdiscord fork is depreciated. Seems that at least for Arch, betterdiscordctl or betterdiscord-rauenzi from the AUR seem to be updated and running.
That said, I've done a fast check on betterdiscordctl and manually injected the style.css contents into the custom css location and it worked identically. I would recommend using beautiful discord for future troubleshooting as it omits factors (not necessarily incompatible with betterdiscord either and is very lightweight.) 
The command you want to get beautifuldiscord to work and make sure wal-discord refreshes would be `wal-discord; beautifuldiscord --css ~/.cache/wal-discord/style.css`.

_my comments on software I'm not familiar with aside;_
Could you do a manual check on the following two files files located at `~/.config/wal-discord/master.scss` and `~/.dache/wal-discord/style.css` to see if they are identical across both machines? Them being different in structure would mean there is a problem with the file generation and them being identical would indicate the problem is instead in applying the theme.

I personally suspect it's a configuration error somewhere, either with betterdiscord or somewhere with the file linking/handling, because the screenshot is almost identical to the old css we had, before #11 was fixed. Aka somewhere the css isn't going where it needs to.

**Comment by GideonWolfe** [comment]
> I don't have too much knowledge of betterdiscord, besides the fact that the base betterdiscord fork is depreciated. Seems that at least for Arch, betterdiscordctl or betterdiscord-rauenzi from the AUR seem to be updated and running.

I should have specified, this is the fork I'm running. 

[diffmaster.txt](https://github.com/guglicap/wal-discord/files/4679122/diffmaster.txt)
[diffstyle.txt](https://github.com/guglicap/wal-discord/files/4679123/diffstyle.txt)

These files are very different it seems

Also, running the above `beautifuldiscord` command did not fail but also did not correctly adjust colors. It looked very similar to the incomplete theme generated by `wal-discord`. Or it is exactly that theme since I pointed `beautifuldiscord` at it.

**Comment by VGrol** [comment]
Seems that the master file is not updated properly, meaning that the theme that generates is still based off of the old broken code. I think the system link just got tangled up into some stuff, doesn't seem to be an issue with betterdiscord at the very least.

Could you pease try the following?
`cd` to your git repo of wal-discord, 
remove the master.scss ln by executing the following command `rm ~/.config/wal-discord/master.scss`
double check the repo is up to date through `git pull` (should go off without a hitch and prompt it is already up to date.)
then recreate the file link by executing `ln -s [git repo location of wal-discord]/config/master.scss] ~/.config/wal-discord/master.scss`.

This should allow you to run `wal-discord` again and generate an updated theme.

**Comment by GideonWolfe** [comment]
That did it!

It looks like `beautifuldiscord` auto injected the CSS when I created the new symlink.

Thanks for the help!
