### ISSUE TITLE
Master.css no such file or directory

### ISSUE THREAD

**Issue by Ferryistaken** [guglicap/wal-discord#31]
I ran wal-discord -t, and it just says that `$HOME/.config/wal-discord/master.scss` does not exists, but it exists and it is a symlink to `./config/master.css`. I followed the installation instructions but didn't get it to work at all

**Comment by guglicap** [comment]
could you please post the output of `ls -l ~/.config/wal-discord`? thanks

**Comment by Ferryistaken** [comment]
> could you please post the output of `ls -l ~/.config/wal-discord`? thanks

I reinstalled and everything worked fine. I probably messed up something in the installation. Sorry for the late reply.

**Comment by gBasil** [comment]
Sorry for a necropost, but this seems like an issue with the symlinks.

**Comment by Ferryistaken** [comment]
Will keep in mind if it happens again

**Comment by sortedcord** [comment]
I am having the same issue. How did you get it to work?

Here is an output of `ls -l ~/.config/wal-discord`
```
total 0
lrwxrwxrwx 1 codegrity codegrity 17 Feb 20 18:52 backends -> ./config/backends
lrwxrwxrwx 1 codegrity codegrity 17 Feb 20 18:52 backend.scss -> backends/wal.scss
lrwxrwxrwx 1 codegrity codegrity 38 Feb 20 18:52 colors.scss -> /home/codegrity/.cache/wal/colors.scss
lrwxrwxrwx 1 codegrity codegrity 20 Feb 20 18:52 master.scss -> ./config/master.scss
```

**Comment by guglicap** [comment]
@sortedcord that indeed looks like an issue with the symlinks. It doesn't quite look like something the setup script could've messed up, though. You should try running `wal-discord -u` from the directory created by `git clone`. 

To clear things up, `backends` and `master.scss` don't need to be symlinks, although symlinking them to the `config` folder in the repo dir makes it so that if you run `git pull` to update wal-discord, they get updated automatically.
